services:
  - type: web
    name: blogapp-backend
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_api.wsgi:application"
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.pbltwarauxcbicrybccx:blogapplication971@db.pbltwarauxcbicrybccx.supabase.co:5432/postgres
