// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbltwarauxcbicrybccx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBibHR3YXJhdXhjYmljcnliY2N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzMzMDcsImV4cCI6MjA3NDE0OTMwN30.8j5mE6PmWz0Q-J8jRJDidQ-3hbf3ELiMptcBBDY3muk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});